### ISSUE TITLE
'make check' fails

### ISSUE THREAD

**Issue by tomfitzhenry** [google/libnss-cache#10]
`make check` fails for a variety of reasons including that it depends on gen_cache.py which isn't in this VCS.

**Comment by tomfitzhenry** [comment]
I managed to get them passing locally, with a few changes that aren't yet PR-worthy.

https://github.com/tomfitzhenry/libnss-cache/commit/c942a1a58144d3be4e78de2dd0d25b20335ee74f is my attempt, in case anyone gets to it before I tidy it up.

**Comment by jaqx0r** [comment]
It's looking good.  Woops about leaving that gen_cache.py reference in
there, but looks like you figured out what it did :)  Thanks!

**Comment by jaqx0r** [comment]
This seems fixed now as of #13 but your gen_cache.go might still be useful.
