### ISSUE TITLE
cache not working on centos.

### ISSUE THREAD

**Issue by marranz** [google/libnss-cache#17]
I´m configuring nsscache for caching ldap credentials on /etc/passwd.cache and then make the magic with libnss-cache.

On ubuntu i´m not having any kind of problem, but on centos it doesn´t look like getent passwd <user> is getting the user list from the cached passwd.

Could it be caused by the location of libnss_cache.so.2.0? i tried moving it to /usr/lib/, /usr/lib64/ and /usr/lib64/nss and no luck so far
Anyone has any experience making it work on centOS 7?

I tried to find something using strace in front of the nsscache command but can´t find nothing of value.

Cheers

**Comment by jaqx0r** [comment]
Did you figure out what the problem was?
