### ISSUE TITLE
Packaging for Debian multiarch

### ISSUE THREAD

**Issue by dnschneid** [google/libnss-cache#6]
Unless I'm totally overlooking something, this library doesn't appear to be configured properly for Debian multiarch support.  See https://wiki.debian.org/Multiarch/Implementation

**Comment by jaqx0r** [comment]
Are you getting specific errors you can share?

**Comment by dnschneid** [comment]
Mainly that for any Debian distribution, the x86_64 version and i386 version of the package cannot be installed at the same time, preventing 32-bit executables that need this library from coexisting on the system.  Both architecture packages in the Debian and Ubuntu repositories try to control /usr/lib/libnss-cache.so.2.  A multiarch-supporting package would install to /usr/lib/$arch/libnss-cache.so.2.

**Comment by jaqx0r** [comment]
ah ok, thanks!

**Comment by dnschneid** [comment]
Whoa, thanks for the quick response!  Doesn't `Multi-Arch: same` need to be added to debian/control, though?

**Comment by jaqx0r** [comment]
I haven't built a new release yet, so probably it does and I haven't found
that bug yet :)
